"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aramexTestCredentials = exports.createAramexAddress = exports.calculateAramexChargeableWeight = exports.initializeAramexClient = exports.requestAramexReturn = exports.requestAramexDelivery = exports.getAramexShippingCost = exports.getAramexShipmentStatus = void 0;
const aramex_1 = require("./aramex");
Object.defineProperty(exports, "aramexTestCredentials", { enumerable: true, get: function () { return aramex_1.aramexTestCredentials; } });
Object.defineProperty(exports, "calculateAramexChargeableWeight", { enumerable: true, get: function () { return aramex_1.calculateAramexChargeableWeight; } });
Object.defineProperty(exports, "createAramexAddress", { enumerable: true, get: function () { return aramex_1.createAramexAddress; } });
Object.defineProperty(exports, "getAramexShipmentStatus", { enumerable: true, get: function () { return aramex_1.getAramexShipmentStatus; } });
Object.defineProperty(exports, "getAramexShippingCost", { enumerable: true, get: function () { return aramex_1.getAramexShippingCost; } });
Object.defineProperty(exports, "initializeAramexClient", { enumerable: true, get: function () { return aramex_1.initializeAramexClient; } });
Object.defineProperty(exports, "requestAramexDelivery", { enumerable: true, get: function () { return aramex_1.requestAramexDelivery; } });
Object.defineProperty(exports, "requestAramexReturn", { enumerable: true, get: function () { return aramex_1.requestAramexReturn; } });
